var data = { 
    "eye_colour":{ 
        "dark_brown": {
            "photosynthesise_sunlight": -5,
            "echolocation": +2,
            "night_vision": +5,
            "halve_need_for_sleep": +4,
            "limb_regeneration": 0,
            "no_wrinkles": 0,
            "mood_dependant_iris_colour": -3,
            "superhuman_strength": 0,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": +3,
            "increase_lucid_dream": 0,
            "fast_reaction_time": 0
        },
        "light_brown": {
            "photosynthesise_sunlight": -2,
            "echolocation": +1,
            "night_vision": +3,
            "halve_need_for_sleep": 0,
            "limb_regeneration": 0,
            "no_wrinkles": 0,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": 0,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": +3,
            "increase_lucid_dream": 0,
            "fast_reaction_time": 0
        },
        "hazelnut": {
            "photosynthesise_sunlight": +2,
            "echolocation": 0,
            "night_vision": 0,
            "halve_need_for_sleep": 0,
            "limb_regeneration": 0,
            "no_wrinkles": 0,
            "mood_dependant_iris_colour": +2,
            "superhuman_strength": 0,
            "superhuman_vision": +1,
            "superhuman_colour_vision": +3,
            "photographic_memory": +1,
            "increase_lucid_dream": 0,
            "fast_reaction_time": +1
        },
        "green": {
            "photosynthesise_sunlight": +5,
            "echolocation": 0,
            "night_vision": +5,
            "halve_need_for_sleep": -3,
            "limb_regeneration": 0,
            "no_wrinkles": 0,
            "mood_dependant_iris_colour": +3,
            "superhuman_strength": 0,
            "superhuman_vision": 0,
            "superhuman_colour_vision": +5,
            "photographic_memory": 0,
            "increase_lucid_dream": 0,
            "fast_reaction_time": +2
        },
        "blue": {
            "photosynthesise_sunlight": +3,
            "echolocation": 0,
            "night_vision": -1,
            "halve_need_for_sleep": -2,
            "limb_regeneration": 0,
            "no_wrinkles": 0,
            "mood_dependant_iris_colour": +5,
            "superhuman_strength": 0,
            "superhuman_vision": +5,
            "superhuman_colour_vision": 0,
            "photographic_memory": 0,
            "increase_lucid_dream": 0,
            "fast_reaction_time": +3
        },
        "none": {
            "photosynthesise_sunlight": 0,
            "echolocation": 0,
            "night_vision": 0,
            "halve_need_for_sleep": 0,
            "limb_regeneration": 0,
            "no_wrinkles": 0,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": 0,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": 0,
            "increase_lucid_dream": 0,
            "fast_reaction_time": 0
        
        }
    },
    
//----------------
    
    "skin_colour":{ 
        "very_fair": {
            "photosynthesise_sunlight": -5,
            "echolocation": +2,
            "night_vision": +2,
            "halve_need_for_sleep": 0,
            "limb_regeneration": 0,
            "no_wrinkles": -5,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": -5,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": 0,
            "increase_lucid_dream": 0,
            "fast_reaction_time": 0
        },
        "fair": {
            "photosynthesise_sunlight": -3,
            "echolocation": +1,
            "night_vision": +1,
            "halve_need_for_sleep": 0,
            "limb_regeneration": 0,
            "no_wrinkles": 0,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": -3,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": 0,
            "increase_lucid_dream": 0,
            "fast_reaction_time": 0
        },
        "olive": {
            "photosynthesise_sunlight": 0,
            "echolocation": 0,
            "night_vision": 0,
            "halve_need_for_sleep": 0,
            "limb_regeneration": 0,
            "no_wrinkles": +5,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": +2,
            "superhuman_vision": 0,
            "superhuman_colour_vision": +3,
            "photographic_memory": 0,
            "increase_lucid_dream": 0,
            "fast_reaction_time": 0
        },
        "brown": {
            "photosynthesise_sunlight": +3,
            "echolocation": -1,
            "night_vision": -1,
            "halve_need_for_sleep": 0,
            "limb_regeneration": 0,
            "no_wrinkles": +3,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": +3,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": 0,
            "increase_lucid_dream": 0,
            "fast_reaction_time": 0
        },
        "black": {
            "photosynthesise_sunlight": +5,
            "echolocation": -2,
            "night_vision": -2,
            "halve_need_for_sleep": 0,
            "limb_regeneration": 0,
            "no_wrinkles": -5,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": +5,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": 0,
            "increase_lucid_dream": 0,
            "fast_reaction_time": 0
        },
        "none": {
            "photosynthesise_sunlight": 0,
            "echolocation": 0,
            "night_vision": 0,
            "halve_need_for_sleep": 0,
            "limb_regeneration": 0,
            "no_wrinkles": 0,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": 0,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": 0,
            "increase_lucid_dream": 0,
            "fast_reaction_time": 0
        
        }
    },
    
    //----------------
    
    "hair_colour":{ 
        "blonde": {
            "photosynthesise_sunlight": -5,
            "echolocation": +2,
            "night_vision": 0,
            "halve_need_for_sleep": 0,
            "limb_regeneration": +3,
            "no_wrinkles": +3,
            "mood_dependant_iris_colour": +3,
            "superhuman_strength": -3,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": 0,
            "increase_lucid_dream": -3,
            "fast_reaction_time": -2
        },
        "gold": {
            "photosynthesise_sunlight": -3,
            "echolocation": 0,
            "night_vision": 0,
            "halve_need_for_sleep": 0,
            "limb_regeneration": +3,
            "no_wrinkles": +3,
            "mood_dependant_iris_colour": -2,
            "superhuman_strength": 0,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": 0,
            "increase_lucid_dream": 0,
            "fast_reaction_time": -1
        },
        "red": {
            "photosynthesise_sunlight": 0,
            "echolocation": -2,
            "night_vision": 0,
            "halve_need_for_sleep": 0,
            "limb_regeneration": 0,
            "no_wrinkles": 0,
            "mood_dependant_iris_colour": +5,
            "superhuman_strength": 0,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": 0,
            "increase_lucid_dream": +5,
            "fast_reaction_time": 0
        },
        "brown": {
            "photosynthesise_sunlight": +3,
            "echolocation": +3,
            "night_vision": 0,
            "halve_need_for_sleep": 0,
            "limb_regeneration": -2,
            "no_wrinkles": 0,
            "mood_dependant_iris_colour": -5,
            "superhuman_strength": +5,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": 0,
            "increase_lucid_dream": -5,
            "fast_reaction_time": +1
        },
        "black": {
            "photosynthesise_sunlight": +5,
            "echolocation": -1,
            "night_vision": 0,
            "halve_need_for_sleep": 0,
            "limb_regeneration": +1,
            "no_wrinkles": 0,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": +3,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": 0,
            "increase_lucid_dream": +3,
            "fast_reaction_time": +1
        },
        "none": {
            "photosynthesise_sunlight": 0,
            "echolocation": 0,
            "night_vision": 0,
            "halve_need_for_sleep": 0,
            "limb_regeneration": 0,
            "no_wrinkles": 0,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": 0,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": 0,
            "increase_lucid_dream": 0,
            "fast_reaction_time": 0
        
        }
    },
    //----------------
    
    "ear_shape":{ 
        "ear_1": {
            "photosynthesise_sunlight": 0,
            "echolocation": -1,
            "night_vision": 0,
            "halve_need_for_sleep": -2,
            "limb_regeneration": -1,
            "no_wrinkles": +3,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": -1,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": 0,
            "increase_lucid_dream": 0,
            "fast_reaction_time": +1
        },
        "ear_2": {
            "photosynthesise_sunlight": 0,
            "echolocation": -2,
            "night_vision": 0,
            "halve_need_for_sleep": +2,
            "limb_regeneration": -2,
            "no_wrinkles": +2,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": 0,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": 0,
            "increase_lucid_dream": -1,
            "fast_reaction_time": -1
        },
        "ear_3": {
            "photosynthesise_sunlight": 0,
            "echolocation": +3,
            "night_vision": 0,
            "halve_need_for_sleep": -1,
            "limb_regeneration": -3,
            "no_wrinkles": 0,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": +2,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": 0,
            "increase_lucid_dream": +3,
            "fast_reaction_time": -2
        },
        "ear_4": {
            "photosynthesise_sunlight": 0,
            "echolocation": +5,
            "night_vision": 0,
            "halve_need_for_sleep": +1,
            "limb_regeneration": 0,
            "no_wrinkles": -3,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": +2,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": 0,
            "increase_lucid_dream": +1,
            "fast_reaction_time": 0
        },
        "ear_5": {
            "photosynthesise_sunlight": 0,
            "echolocation": 0,
            "night_vision": 0,
            "halve_need_for_sleep": 0,
            "limb_regeneration": +1,
            "no_wrinkles": -5,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": +3,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": 0,
            "increase_lucid_dream": 0,
            "fast_reaction_time": +1
        },
        "none": {
            "photosynthesise_sunlight": 0,
            "echolocation": 0,
            "night_vision": 0,
            "halve_need_for_sleep": 0,
            "limb_regeneration": 0,
            "no_wrinkles": 0,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": 0,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": 0,
            "increase_lucid_dream": 0,
            "fast_reaction_time": 0
        }
    },
    //----------------
    
    "eyebrow_shape":{ 
        "no_eyebrow": {
            "photosynthesise_sunlight": -5,
            "echolocation": 0,
            "night_vision": 0,
            "halve_need_for_sleep": +5,
            "limb_regeneration": -5,
            "no_wrinkles": +1,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": -5,
            "superhuman_vision": +1,
            "superhuman_colour_vision": 0,
            "photographic_memory": +1,
            "increase_lucid_dream": 0,
            "fast_reaction_time": +3
        },
        "straight": {
            "photosynthesise_sunlight": -3,
            "echolocation": 0,
            "night_vision": 0,
            "halve_need_for_sleep": +3,
            "limb_regeneration": 0,
            "no_wrinkles": 0,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": -2,
            "superhuman_vision": +5,
            "superhuman_colour_vision": 0,
            "photographic_memory": +3,
            "increase_lucid_dream": 0,
            "fast_reaction_time": +2
        },
        "rounded": {
            "photosynthesise_sunlight": 0,
            "echolocation": 0,
            "night_vision": 0,
            "halve_need_for_sleep": -2,
            "limb_regeneration": 0,
            "no_wrinkles": +2,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": 0,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": +5,
            "increase_lucid_dream": 0,
            "fast_reaction_time": 0
        },
        
        "angled_arch": {
            "photosynthesise_sunlight": +5,
            "echolocation": 0,
            "night_vision": 0,
            "halve_need_for_sleep": 0,
            "limb_regeneration": 0,
            "no_wrinkles": -4,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": +3,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": -3,
            "increase_lucid_dream": 0,
            "fast_reaction_time": -2
        },
        "s_shape": {
            "photosynthesise_sunlight": +3,
            "echolocation": 0,
            "night_vision": 0,
            "halve_need_for_sleep": -3,
            "limb_regeneration": 0,
            "no_wrinkles": +4,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": +5,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": -1,
            "increase_lucid_dream": 0,
            "fast_reaction_time": -3
        },
        "none": {
            "photosynthesise_sunlight": 0,
            "echolocation": 0,
            "night_vision": 0,
            "halve_need_for_sleep": 0,
            "limb_regeneration": 0,
            "no_wrinkles": 0,
            "mood_dependant_iris_colour": 0,
            "superhuman_strength": 0,
            "superhuman_vision": 0,
            "superhuman_colour_vision": 0,
            "photographic_memory": 0,
            "increase_lucid_dream": 0,
            "fast_reaction_time": 0
        }
        
    }
    
}

